[package]
name = "moneybags"
version = "0.1.0"
edition = "2021"
license = "MIT"
readme = "README.md"
publish = false

[dependencies]
anyhow = "1"
csv = "1"
fixed = "1"
serde = { version = "1", features = ["derive"] }
serde_plain = "1"
